name: go format

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  statictest:
    runs-on: ubuntu-latest
    container: golang:1.19
    steps:
      - name: Check code formatting using gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
