name: staticcheck

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  statictest:
    runs-on: ubuntu-latest
    container: golang:1.19
    steps:
      - uses: actions/checkout@v1
        with:
        fetch-depth: 1
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
        version: "2022.1.1"
