name: staticcheck

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  statictest:
    runs-on: ubuntu-latest
    container: golang:1.19
    steps:
      - name: Staticcheck run for golang code
        uses: dominikh/staticcheck-action@v1.2.0

